export const WAITING_QUOTES = [
  'Your teacher is probably arranging spies with the seriousness of a movie trailer.',
  'A clipboard somewhere just became much more powerful than it should be.',
  'This pause is sponsored by dramatic team sorting and imaginary spy paperwork.',
  'Someone is almost certainly deciding whether you feel more red-team or blue-team today.',
  'The board is warming up its rectangle muscles for the next round.',
  'A secret meeting is happening, and it may only involve dragging names into boxes.',
  'The classroom spies are currently in pre-launch snackless mode.',
  'Patience is just stealth practiced very, very slowly.',
  'The captain rotation is being forged in the gentle fires of organization.',
  'A highly trained lobby is doing absolutely nothing at incredible speed.',
  'Somewhere nearby, a teacher is making mysterious choices on purpose.',
  'The cards have not moved, but morale remains under observation.',
  'A neutral card believes in you even if it should not.',
  'The assassin card is being dramatic again. Please ignore its energy.',
  'This waiting screen has been approved by the Department of Mild Suspense.',
  'The next clue is currently hiding behind adult decision making.',
  'A room code has never felt more important than it does right now.',
  'The projector is dreaming of a grand reveal and slightly crooked alignment.',
  'Every spy squad needs one calm moment before the chaos begins.',
  'The board would like you to know it has several strong opinions about rectangles.',
  'Some heroes wear capes. Others just wait quietly for assignments.',
  'An invisible drumroll is happening in the background of this exact moment.',
  'This silence is not empty. It is full of upcoming guesses.',
  'Even the chat panel would tell you to hang tight right now.',
  'A future captain is probably pretending not to be excited.',
  'The clue has not arrived yet, but the vibes are cautiously professional.',
  'The tiles are standing by with excellent posture.',
  'Spy work involves more waiting than the movies usually mention.',
  'A glorious incorrect guess is being prevented by setup logistics.',
  'The board appreciates your commitment to stylish patience.',
  'The room is currently 12 percent strategy and 88 percent staging.',
  'There is no rush. There is only suspense wearing classroom shoes.',
  'A tiny invisible owl is supervising the lobby and nodding wisely.',
  'Your mission, should you choose to accept it, is to keep existing for another moment.',
  'The teams are being arranged with the precision of a very nervous orchestra.',
  'This quote card is working harder than some office printers.',
  'A brilliant clue may be forming, or someone may still be finding the start button.',
  'The red team and blue team are probably judging each other already.',
  'The lobby air smells faintly of strategy and dry erase markers.',
  'An important looking countdown is taking the day off.',
  'If waiting were a sport, you would currently be seeded very well.',
  'The board is not late. It is building anticipation with confidence.',
  'A secret agent once called this part character development.',
  'The next phase is loading with maximum educational suspense.',
  'A clever guess is out there somewhere doing stretches.',
  'This card flips because standing still all day felt too ordinary.',
  'You are not stuck. You are marinating in potential.',
  'Somewhere, a spymaster is preparing a clue with suspicious confidence.',
  'The classroom universe is aligning one draggable player chip at a time.',
  'All great missions begin with someone saying, "Hold on one second."'
] as const;
